[package]
name = "badder_lang"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
log = "0.4"
string_cache = "0.7"
single_value_channel = "1"
strsim = "0.7"
indexmap = "1"

[dev-dependencies]
env_logger = "0.5"
assert_matches = "1"
