[package]
name = "badder_lang"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
log = "0.3"
string_cache = "0.7"
single_value_channel = "1"
strsim = "0.6"
ordermap = "0.3"

[dev-dependencies]
pretty_env_logger = "0.1"
assert_matches = "1"
